@baseUrl = http://localhost:3434

POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Daniel Borges",
  "email": "dlopesborges@gmail.com",
  "googleId": "123456"
}

###

POST {{baseUrl}}/tabs
Content-Type: application/json

{
  "ownerId": "7f8506d1-55f9-4e24-9915-6d00a11f9d77",
  "title": "conta 14-07-2025"
}

###

POST {{baseUrl}}/items
Content-Type: application/json

{
  "tabId": "d8000164-2a63-4f8b-9ab3-002351af79f4",
  "description": "coca lata",
  "unitPrice": "8.00",
  "quantity": 1,
  "createdBy": "Daniel Borges"
}

###

GET {{baseUrl}}/tabs/d8000164-2a63-4f8b-9ab3-002351af79f4/items

###

POST {{baseUrl}}/participants
Content-Type: application/json

{
  "tabId": "f11310c4-c856-458b-9ae8-00b8268b0f29",
  "name": "Edmar Marinho"
}

###

GET {{baseUrl}}/tabs/f11310c4-c856-458b-9ae8-00b8268b0f29/participants

###

POST {{baseUrl}}/parts
Content-Type: application/json

{
  "itemId": "0314bd7e-8e26-42aa-a0ae-373c15b416d5",
  "partsCount": 1,
  "participantId": "62476f03-d280-4d8a-bd12-4d55a686a18a",
  "tabId": "d8000164-2a63-4f8b-9ab3-002351af79f4"
}

###

GET {{baseUrl}}/items/0314bd7e-8e26-42aa-a0ae-373c15b416d5/parts
